---
- name: Main playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: executing site_vms role
      include_role:
        name: sites_vm_inventory

    - name: executing site_devices role
      include_role:
        name: sites_devices_inventory
