---
- name: Create INI inventory from YAML
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Include variables file
      include_vars:
        file: ../ansible_vault/netbox-token.yaml

    - name: create an netbox_inventory file
      template:
        src: ../templates/netbox_inventory.j2
        dest: ./netbox_inventory.yaml

    - name: Create YAML inventory if not exists
      shell: "ansible-inventory -i netbox_inventory.yaml --list -y > inv.yaml"
      
    - name: Read YAML inventory
      slurp:
        src: inv.yaml
      register: yaml_inventory

    - name: Convert YAML to JSON
      set_fact:
        json_inventory: "{{ yaml_inventory.content | b64decode | from_yaml }}"

    - name: Check if inventory.ini exists
      stat:
        path: inventory.ini
      register: ini_file

    - name: Create inventory.ini file if absent
      copy:
        content: |
          # Inventory file created by Ansible playbook
        dest: inventory.ini
      when: ini_file.stat.exists == false

    - name: Generate INI inventory
      copy:
        content: |
          {% for site_name, site_data in json_inventory.all.children.items() %}
          
          [{{ site_name }}]
          
          {% for host_name, host_data in site_data.hosts.items() %}
          {{ host_name }}
          {% endfor %}
          {% endfor %}
        dest: inventory.ini

    - name: Remove inv.yaml file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - inv.yml
        - netbox_inventory.yaml
