---
- name: Create INI inventory from YAML
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Create YAML inventory if not exists
      shell: "ansible-inventory -i netbox_inventory.yaml --list -y > inv.yaml"
      
    - name: Read YAML inventory
      slurp:
        src: inv.yaml
      register: yaml_inventory

    - name: Convert YAML to JSON
      set_fact:
        json_inventory: "{{ yaml_inventory.content | b64decode | from_yaml }}"

    - name: Check if inventory.ini exists
      stat:
        path: inventory.ini
      register: ini_file

    - name: Create inventory.ini file if absent
      copy:
        content: |
          # Empty inventory file created by Ansible playbook
        dest: inventory.ini
      when: ini_file.stat.exists == False
        
    - name: Generate INI inventory
      copy:
        content: |
          {% for group, group_data in json_inventory.all.children.items() %}
          
          {% if group_data.children %}
          [{{ group }}]
          
          {% for site, site_data in group_data.children.items() %}
          {% if site_data.hosts %}
          [{{ site }}]
          {% for host, host_data in site_data.hosts.items() %}
          {{ host }}
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% endfor %}
        dest: inventory.ini

    - name: Remove inv.yaml file
      file:
        path: inv.yaml
        state: absent
      
