---
- name: Fetch devices data from NetBox
  uri:
    url: "{{ netbox_api }}api/dcim/devices/"
    method: GET
    headers:
      Authorization: "Token {{ netbox_token }}"
    return_content: yes
  register: netbox_devices

- name: Extract site names from NetBox VM data
  set_fact:
    site_names: "{{ netbox_devices.json.results | map(attribute='site') | select('defined') | map(attribute='name') | select('defined') | unique | list }}"

- name: Ensure the destination directory exists
  file:
    path: "roles/sites_devices_inventory/hosts/"
    state: directory
- name: Debug - Check if directory exists
  stat:
    path: "roles/sites_devices_inventory/hosts/"
  register: directory_exists

- name: Debug - Check directory existence result
  debug:
    var: directory_exists

- name: Copy VM inventory template
  template:
    src: devices_inventory.ini.j2
    dest: "roles/sites_devices_inventory/hosts/devices_inventory.ini"

- name: Debug - Check copied file
  shell: cat roles/sites_devices_inventory/hosts/devices_inventory.ini
  ignore_errors: true
