---
- name: Example playbook accessing GitHub secrets
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Access NetBox API token from GitHub secrets
      shell: echo $NETBOX_TOKEN
      environment:
        NETBOX_API_TOKEN: "{{ lookup('env', 'NETBOX_TOKEN') }}"
      register: netbox_token_result

    - set_fact:
        netbox_token: "{{ netbox_token_result.stdout }}"

    - debug:
        msg: "NetBox API token is {{ netbox_token }}"
