---
- name: Fetch VM data from NetBox
  uri:
    url: "{{ netbox_api }}api/virtualization/virtual-machines/"
    method: GET
    headers:
      Authorization: "Token {{ netbox_token }}"
    return_content: yes
  register: netbox_vms

- name: Extract site names from NetBox VM data
  set_fact:
    site_names: "{{ netbox_vms.json.results | map(attribute='site') | select('defined') | map(attribute='name') | select('defined') | unique | list }}"

- name: Ensure the destination directory exists
  file:
    path: "roles/sites_vm_inventory/hosts/"
    state: directory

- name: Copy VM inventory template
  template:
    src: vm_inventory.ini.j2
    dest: "roles/sites_vm_inventory/hosts/vm_inventory.ini"
