name: Ansible Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
      env:
        NETBOX_API: ${{ secrets.NETBOX_API }}
        NETBOX_TOKEN: ${{ secrets.NETBOX_TOKEN }}
