name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install ansible

      - name: Create environment file
        run: |
          echo "netbox_api: ${{ secrets.NETBOX_API }}" > env.list
          echo "netbox_token: ${{ secrets.NETBOX_TOKEN }}" >> env.list
      
      - name: Display fetched secrets
        run: cat env.list
      
      - name: Run Ansible playbook with secrets as variables
        run: |
          ansible-playbook main1.yaml --extra-vars "@env.list" -v
        env:
          ANSIBLE_CONFIG: ansible.cfg

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add roles/sites_devices_inventory/hosts/devices_inventory.ini
          git commit -m "Update devices inventory"
          git push origin main
